"""Update Students and Users

Revision ID: 6bafc970a13d
Revises: f95b0a1dc392
Create Date: 2022-01-27 17:14:59.123436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bafc970a13d'
down_revision = 'f95b0a1dc392'
branch_labels = None
depends_on = None

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None, naming_convention=convention) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_student_userID_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('userID')
        batch_op.drop_column('studentEmail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentEmail', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('userID', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_student_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userID'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
