"""Set Up Initial Databases

Revision ID: 8bd8fd1497bb
Revises: a51dd5f8ea2f
Create Date: 2021-11-26 13:58:50.291113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd8fd1497bb'
down_revision = 'a51dd5f8ea2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address1', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zipCode', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('numberEmployees', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advocate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=True),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('linkedin', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('numberHelped', sa.Integer(), nullable=True),
    sa.Column('companyStart', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('noteType', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=True),
    sa.Column('middleName', sa.String(length=128), nullable=True),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('studentEmail', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('classYear', sa.String(length=4), nullable=True),
    sa.Column('linkedIn', sa.String(length=128), nullable=True),
    sa.Column('intent', sa.String(length=128), nullable=True),
    sa.Column('attitude', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('lastUpdate', sa.DateTime(), nullable=True),
    sa.Column('jobStatus', sa.String(length=64), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('degree', sa.String(length=64), nullable=True),
    sa.Column('program', sa.String(length=64), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('advocateId', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('helpful', sa.String(length=10), nullable=True),
    sa.Column('gaveRef', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['advocateId'], ['advocate.id'], ),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('interestLevel', sa.Integer(), nullable=True),
    sa.Column('confidenceLevel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('interestLevel', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('movingExpenses', sa.Boolean(), nullable=True),
    sa.Column('stockOptions', sa.Boolean(), nullable=True),
    sa.Column('totalPackage', sa.Float(), nullable=True),
    sa.Column('intention', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lamp_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('interviewerName', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_interview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('round', sa.String(length=10), nullable=True),
    sa.Column('offerConfidence', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('jobTitle', sa.String(length=128), nullable=True),
    sa.Column('compensation', sa.String(length=32), nullable=True),
    sa.Column('duties', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['companyId'], ['company.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('noteType', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['studentId'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_note')
    op.drop_table('resume')
    op.drop_table('real_interview')
    op.drop_table('mock_interview')
    op.drop_table('lamp_list')
    op.drop_table('job_offer')
    op.drop_table('job_application')
    op.drop_table('info_interview')
    op.drop_table('education')
    op.drop_table('student')
    op.drop_table('company_note')
    op.drop_table('advocate')
    op.drop_table('company')
    # ### end Alembic commands ###
