"""Create Student

Revision ID: b30f8c2b916b
Revises: 
Create Date: 2021-12-01 13:56:35.132922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b30f8c2b916b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=32), nullable=False),
    sa.Column('lastName', sa.String(length=32), nullable=False),
    sa.Column('classYear', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(length=32), nullable=True),
    sa.Column('mentor', sa.String(length=64), nullable=True),
    sa.Column('interest', sa.String(length=32), nullable=True),
    sa.Column('profileImage', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_firstName'), 'student', ['firstName'], unique=False)
    op.create_index(op.f('ix_student_lastName'), 'student', ['lastName'], unique=False)
    op.create_index(op.f('ix_student_mentor'), 'student', ['mentor'], unique=False)
    op.create_index(op.f('ix_student_track'), 'student', ['track'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_track'), table_name='student')
    op.drop_index(op.f('ix_student_mentor'), table_name='student')
    op.drop_index(op.f('ix_student_lastName'), table_name='student')
    op.drop_index(op.f('ix_student_firstName'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
