"""Update Student for all fields

Revision ID: f95b0a1dc392
Revises: 88917844cdb0
Create Date: 2022-01-11 17:15:03.485661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95b0a1dc392'
down_revision = '88917844cdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('mentor', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('interest', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('profileImagePath', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('profileImagePath')
        batch_op.drop_column('interest')
        batch_op.drop_column('mentor')
        batch_op.drop_column('track')

    # ### end Alembic commands ###
